### PR TITLE
Add logging template

### PR DESCRIPTION
**Pull request by JakubKotkowiak**

### CODE REVIEW

**Review by zelaskov — APPROVED** [review]

**Review by rubenruizdegauna — APPROVED** [review]
LGTM

**Comment by gdevdeiv** [comment]
+1! I was just searching for a way to enable log forwarding to New Relic, would be good to have this merged. Do you have an estimation?

**Comment by gdevdeiv** [comment]
It would be nice if `nrinfragent_logging` allowed an array, that would mean we could define a list of log sources, each one with its type and config.

Btw, as a note: it looks like [log forwarding isn't ready yet in ARM architecture](https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/forward-your-logs-using-infrastructure-agent/#install) (see the green TIP section)!

**Comment by JakubKotkowiak** [comment]
> It would be nice if `nrinfragent_logging` allowed an array, that would mean we could define a list of log sources, each one with its type and config.
> 
> Btw, as a note: it looks like [log forwarding isn't ready yet in ARM architecture](https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/forward-your-logs-using-infrastructure-agent/#install) (see the green TIP section)!

Hello @gdevdeiv, this is something that we're currently working on so hopefully soon it should be ready.

**Review by rubenruizdegauna — APPROVED** [review]
LGTM

**Comment by JakubKotkowiak** [comment]
I will be moving it to a separate PR due to some small issues.

**Pull request closed without merging**
