### PR TITLE
Fix logging

### LINKED ISSUE #151: Configuration nrinfragent_logging not working
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

Configuration nrinfragent_logging not working.

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

The nrinfragent_logging configuration does not work. Checking the commit (https://github.com/newrelic/infrastructure-agent-ansible/commit/88d7172ff8abbcbbe61d81fae4fec1cba522cc00) and the files of the last TAG, and master, I do not see that the setup_logging.yml task is imported. Is it a functionality that is not finished yet? If so, do you know when it will be ready? Thanks! 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )

After configure nrinfragent_logging and run ansible i not see in the directory /etc/newrelic-infra/logging.d with my customizations.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

The role is configured as in the example https://github.com/newrelic/infrastructure-agent-ansible/blob/master/defaults/main.yml

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

...

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )

Amazon Linux 2

### PR DESCRIPTION
**Pull request by RulerOf**
Fixes #151 

Needs tests

Edit: tests added 2022-10-23 by @max-franklin

### CODE REVIEW

**Comment by Hokwang** [comment]
I am looking forward to committing this PR.

**Comment by RulerOf** [comment]
@Hokwang I never bothered with the test suite because I couldn't take the time to learn Molecule. Still using Inspec for my server tests ¯\_(ツ)_/¯

**Comment by RulerOf** [comment]
@max-franklin They've got a license thing up above you'll have to sign.

**Comment by max-franklin** [comment]
@RulerOf , thanks for calling that out, I've signed it.

**Review by rubenruizdegauna — APPROVED** [review]
LGTM Thanks for your contribution!

**Comment by max-franklin** [comment]
@rubenruizdegauna , looking at the contributing guide, I'm guessing we need a second person to also review, approve, and potentially merge the changes:

`You may merge the Pull Request in once you have the sign-off of two other developers, or if you do not have permission to do that, you may request the second reviewer to merge it for you.`

**Pull request merged**
