### PR TITLE
Fix task name capitalization for consistency

### PR DESCRIPTION
**Pull request by awilliams219**
While reviewing the code to try to find an issue I was experiencing in my environment, it occurred to me that the task labels are inconsistent with regard to their capitalization.  It's not a big deal, but now I can't un-see it, and rather than complaining about it, here's the fix.  Feel free to merge it if you like.

### CODE REVIEW

**Comment by alejandrodnm** [comment]
HI @awilliams219 thanks for the PR, sorry but we were doing some changes to the repo and ended up changing the name of the file, that's what created the conflict. If it's not too much trouble, would you mind updating the PR? I'll review it as soon as you push it.

Thanks.

**Comment by matiasburni** [comment]
Hi @awilliams219  thanks for your contribution.
Could you rebase your PR please? I'll approve it and merge it.

**Comment by alejandrodnm** [comment]
@awilliams219 I'm going to close the PR, but feel free to reopen it again. Again sorry for the late responses.

**Comment by alejandrodnm** [comment]
@awilliams219  we are fixing this issue in #67 , we decided to go lowercase, thanks for bringing it up.

**Comment by awilliams219** [comment]
No problem.  Hey sorry it took so long for me to comment.  My internet at the house has been spotty this week so I haven't been able to update the PR.

**Pull request closed without merging**
